# Generated by Django 3.2.8 on 2021-10-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_qaror'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qaror',
            name='body',
        ),
        migrations.AddField(
            model_name='qaror',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
