# Generated by Django 3.2.8 on 2021-10-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20211020_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecarusel',
            name='images',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='homenews',
            name='images',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='homevideo',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='xodim',
            name='images',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
