# Generated by Django 3.2.8 on 2021-10-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20211020_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='xodim',
            name='deportment',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
