# Generated by Django 3.2.8 on 2021-10-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_farmon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='sub_title',
            field=models.TextField(),
        ),
    ]
