# Generated by Django 3.2.8 on 2021-10-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_service_sub_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricemodel',
            name='price',
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
