# Generated by Django 3.2.8 on 2021-11-17 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PriceModel',
            new_name='ByudjetModel',
        ),
        migrations.RenameModel(
            old_name='PricingPlan',
            new_name='ByudjetPlan',
        ),
    ]
