# Generated by Django 3.2.8 on 2021-12-22 06:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20211117_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='YangilikModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=150)),
                ('descriptions', models.CharField(max_length=150)),
                ('body', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
