version: '2'

services:
  utsdb_prod:
    container_name: utsdb_prod
    restart: always  
    image: postgres:12.2
    environment:
      POSTGRES_DB: db_uts_prod
      POSTGRES_USER: utsuser_prod
      POSTGRES_PASSWORD: utspass_prod
    networks:
      - uts-network
    volumes:
        - utsdata:/var/lib/postgresql/utsdata/
    
  utsweb_prod:
    container_name: utsweb_prod
    restart: always  
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:3838
    volumes:
      - static_volume_uts:/home/app/web/static
      - media_volume_uts:/home/app/web/media
    networks:
      - uts-network
    depends_on: 
      - utsdb_prod
    ports:
      - "3838:3838"
    env_file: 
      - ./.env.prod

  utsnginx:
    container_name: uts-nginx
    restart: always
    build: ./nginx
    volumes:
      - static_volume_uts:/home/app/web/static
      - media_volume_uts:/home/app/web/media
    ports:
      - "6868:6868"
    networks:
      - uts-network
    depends_on:
      - utsweb_prod
      
volumes:
  utsdata:
  static_volume_uts:
  media_volume_uts:

networks:
  uts-network:
    driver: bridge
